language: python
python:
  - "2.7"
install:
  - pip install codecov
  - pip install -r requirements.txt

script:
  - python unit_testing.py
  - coverage run unit_testing.py

after_success:
  - codecov